[package]
name = "market-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.34"
derive = "1.0.0"
features = "0.10.0"
reqwest = {version="0.11.24", features = ["blocking", "json"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
thiserror = "1.0.57"
url = "2.5.0"


[dev-dependencies]
lazy_static = "1.4.0"
tokio = { version = "1.36", features = ["full"] }

[[example]]
name = "data_from_iexcloud"
path = "examples/data_from_iexcloud.rs"
