name: "Market-Data"
on:
  push:
  pull_request:


env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build
        run: cargo build --verbose
      - name: Run example series_alphavantage
        run: cargo test --example series_alphavantage
      - name: Run example series_iexcloud
        run: cargo test --example series_iexcloud
      - name: Run example series_twelvedata
        run: cargo test --example series_twelvedata
      - name: Run example series_polygon_io
        run: cargo test --example series_polygon_io
      - name: Run example series_yahoo_finance
        run: cargo test --example series_yahoo_finance
      - name: Run example async_series_twelvedata
        run: cargo test --example async_series_twelvedata --features="use-async" --no-default-features

   # Check formatting with rustfmt
  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Ensure rustfmt is installed and setup problem matcher
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1